AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description:  html to pdf conversion

Globals:
  Function:
    Timeout: 30

Resources:

  ## Lambda With API Gateway for converting html to PDF
  pdfLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: index.handler 
      Role: !GetAtt pdfConversionRole.Arn
      Runtime: nodejs12.x
      MemorySize: 512
      Events:
        fileSystem:
          Type: Api
          Properties:
            Path: /download
            Method: POST
  
  ## pdfConversion Lambda Role
  pdfConversionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub pdfLambdaFunction
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  
  # pdfConversionRole Log group
  loggroup:
    Type: AWS::Logs::LogGroup
    DependsOn: pdfLambdaFunction
    Properties:
      RetentionInDays: 14
      LogGroupName: !Join ['',['/aws/lambda',!Ref pdfLambdaFunction]]

Outputs:
  pdfLambdaFunction:
    Description: "html to pdf lambda function ARN"
    Value: !GetAtt pdfLambdaFunction.Arn
  pdfConversionRole:
    Description: "html to pdf IAM Role ARN"
    Value: !GetAtt pdfConversionRole.Arn
  fileSystem:
    Description: "API Gateway endpoint URL for Prod stage for user login function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com"